### ISSUE TITLE
mnnpy package missing

### ISSUE THREAD

**Issue by romanhaa** [FASTGenomics/base_image_alpine_scanpy#2]
I just tried using your Docker container (many thanks that I don't have to prepare one myself!) but I found that the `mnnpy` package seems to be missing. It is required for the `pp.mnn_correct()` function for normalization of batch effects. The package can be found here: https://github.com/chriscainx/mnnpy

Unfortunately, it needs to be compiled, therefore requiring `git` and `gcc` and making the container bigger (~180 MB --> 250 MB). I have installed all the necessary packages, installed `mnnpy` and created a repository in my private hub: https://hub.docker.com/r/romanhaa/scanpy/

**Comment by Jona77** [comment]
Hi!
At the moment we (FASTGenomics) are not using the mnn-algorithm and strangely the installation of scanpy does not automatically install mnnpy. Therefore it is not included into the Dockerfile, yet. There is a pypi-package of mnnpy available at https://pypi.org/project/mnnpy/. Thus it should be installable via: **pip install mnnpy**. Or you could add mmnpy to the requirements.txt.
Then you would still have to put in some manual work, but your Image won't include git and gcc.
Hope this helps.
I'm closing this issue for now.

**Comment by Jona77** [comment]
Hi! Mnnpy is included in the newest version of this image.
